title = "vigoo's software development blog"
author = "Daniel Vigovszky"

base_url = "https://blog.vigoo.dev"
compile_sass = true
build_search_index = false
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]

[markdown.highlighting]
theme = "one-light"

[extra]
